[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install --no-cache-dir --no-deps -r requirements.txt"
]

[phases.build]
cmds = [
  ". /opt/venv/bin/activate && pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "python app.py"

[variables]
PYTHONPATH = "/opt/venv/lib/python3.11/site-packages"
